AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an ECR Repo
Parameters:
  RepositoryName:
    Type: String
    Default: voy/website
    Description: A name for the service

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryPolicyText:
        Version: "2008-10-17"
        Statement:
          - Sid: Allow Push
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::076279718063:user/codyp
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
